Array Manipulation
np.transpose(array) - To transpose array
np.reshape(array,shape) - To Change shape of an array
np.resize(array,shape) - To return new array with shape
np.flatten(array) - To flatten the array
np.transpose()
Transpose is defined as an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by  AT
np.reshape(shape)
Gives a new shape to an array without changing its data.
np.resize(shape)
Changes shape and size of array in-place.
np.flatten()
Returns flattened 1D **arrays**

Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.

arr_1d = np.array([1, 2, 3, 4, 5])**bold text**

In [1]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
a = arr_1d[0]
print(a)

1


Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
a = arr_1d[2:]
print(a)

[3 4 5]


Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
a = arr_2d[1,2]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
a = arr_2d[:1]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]


Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.



arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
a = arr_2d[:,2]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [ ]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
a = arr_3d[1,2,2]
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
18


Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [ ]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
a = arr_3d[0]
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [ ]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
a = arr_3d[1]
a

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])